***CHARMI YASHWANT KANANI***

***GO_STP_755***


### Spam Classification using Multinomial Naive Bayes | Text classification using Multinomial Naive Bayes Example

Build a spam filter using Python and the multinomial Naive Bayes algorithm. Check Spam or Ham? Email Classifier Using Python using MultinomialNB.

In [1]:
!pip install pyforest 
import pyforest

In [2]:
df = pd.read_csv('/content/spam.csv')

<IPython.core.display.Javascript object>

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
var = pd.get_dummies(df['Category'], drop_first = True)
df = df.join(var) 
df.drop('Category', axis = 1, inplace = True)

<IPython.core.display.Javascript object>

In [5]:
df.shape

(5572, 2)

In [6]:
df.isnull().sum()

Message    0
spam       0
dtype: int64

In [7]:
df['spam'].value_counts(normalize = True)

0    0.865937
1    0.134063
Name: spam, dtype: float64

In [8]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
X = df['Message']
y = df['spam']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
train_data = cv.fit_transform(X_train)
train_data.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [10]:
from sklearn.feature_extraction.text import TfidfTransformer
tf = TfidfTransformer()
X_train_tfidf = tf.fit_transform(train_data)
X_train_tfidf.shape

(3900, 7262)

In [11]:
model = MultinomialNB().fit(X_train_tfidf, y_train)

In [12]:
test_data = cv.transform(X_test)

In [13]:
X_test_tfidf = tf.transform(test_data)

In [14]:
pred = model.predict(X_test_tfidf)
pred

array([0, 0, 0, ..., 0, 1, 0], dtype=uint8)

In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [16]:
cm = confusion_matrix(y_test, pred)
cm

array([[1448,    0],
       [  64,  160]])

In [17]:
acc = accuracy_score(y_test, pred)
acc

0.9617224880382775