***CHARMI YASHWANT KANANI***

***GO_STP_755***

NUMPY

1. Import the numpy package under the name np and Print the numpy version and the configuration

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


2. Create a null vector of size 10

In [2]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


3. Create Simple 1-D array and check type and check data types in array

In [3]:
a = np.array([1,2,3])
print(a)
print(type(a))
print(a.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int64


4. How to find number of dimensions, bytes per element and bytes of memory used?

In [4]:
a = np.arange(100)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.size*a.itemsize)

1
100
8
800


5. Create a null vector of size 10 but the fifth value which is 1

In [5]:
a = np.zeros((10))
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6. Create a vector with values ranging from 10 to 49

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

7. Reverse a vector (first element becomes last)

In [7]:
a = np.arange(1,5)
print(a)
a[::-1]

[1 2 3 4]


array([4, 3, 2, 1])

8. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [9]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

10. Create a 3x3 identity matrix

In [10]:
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

11. Create a 3x3x3 array with random values

In [11]:
a = np.random.random((3,3,3))
print(a)

[[[0.73224285 0.05601116 0.26213973]
  [0.95746763 0.9228813  0.08531435]
  [0.09443079 0.05865718 0.5863837 ]]

 [[0.64941263 0.48697242 0.8575147 ]
  [0.10110097 0.78744183 0.38387835]
  [0.97051535 0.63530617 0.64553499]]

 [[0.49700767 0.83952809 0.50045418]
  [0.23446134 0.88423236 0.73070777]
  [0.86750961 0.34701562 0.42188654]]]


12. Create a 10x10 array with random values and find the minimum and maximum values

In [12]:
a = np.random.random((10,10))
print(a.max())
print(a.min())

0.9916744923541846
0.007875994409672349


13. Create a random vector of size 30 and find the mean value

In [13]:
a = np.random.random((30))
print(a)
a.mean()

[0.60275452 0.54344523 0.64350506 0.87557287 0.09822729 0.23010211
 0.64032015 0.8124346  0.80604438 0.7454701  0.22932964 0.55234415
 0.6424504  0.96810726 0.61323969 0.58049527 0.5537595  0.98558225
 0.45883413 0.83526481 0.55631107 0.02731035 0.21558295 0.40962002
 0.74490609 0.18674817 0.06135316 0.04512747 0.43623622 0.43651748]


0.5178998803880546

14. Create a 2d array with 1 on the border and 0 inside

In [14]:
a = np.ones((3,3))
a[1,1] = 0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


15. How to add a border (filled with 0's) around an existing array? 

In [15]:
a = np.arange(1,10).reshape(3,3)
print(a)

a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [16]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a[1,-2]

13

In [17]:
a[0:1,]

array([[1, 2, 3, 4, 5, 6, 7]])

In [18]:
a[:,2:3]

array([[ 3],
       [10]])

In [19]:
a[0,(1,3,5)]

array([2, 4, 6])

In [20]:
a[1,-2] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


17. How to Convert a 1D array to a 2D array with 2 rows

In [21]:
a = np.arange(6)
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

19. Write a program to show how Numpy taking less memory compared to Python List?

In [23]:
l = range(100)
import sys
a = 10
print(sys.getsizeof(a)*len(l))

a = np.arange(100)
print(a.size*a.itemsize)

2800
800


20. Write a program to show how Numpy taking less time compared to Python List?

In [24]:
import time

size = 1000000

l1 = range(size)
l2 = range(size)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)] #list comprehension
print((time.time()-start)*1000)

n1 = np.arange(size)
n2 = np.arange(size)

start = time.time()
result1 = n1+n2
print((time.time()-start)*1000)

127.11238861083984
3.876209259033203
