In [1]:
!pip install pyforest
import pyforest

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [3]:
lr_score = cross_val_score(LogisticRegression(), X, y)
lr_score

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [4]:
np.average(lr_score)

<IPython.core.display.Javascript object>

0.9733333333333334

In [5]:
dt_score = cross_val_score(DecisionTreeClassifier(), X, y)
dt_score

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [6]:
np.average(dt_score)

<IPython.core.display.Javascript object>

0.9533333333333334

In [7]:
svm_score = cross_val_score(SVC(), X, y)
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [8]:
np.average(svm_score)

<IPython.core.display.Javascript object>

0.9666666666666666

In [9]:
# k fold cross validation

from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)