In [ ]:
pip install numpy

In [2]:
import numpy as np

In [ ]:
# one dimensional array
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([[1,2,3], [10,20,30]]) # 2D array

In [ ]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# creating an array of regular intervals 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,3,0.1) # start, stop and difference

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(1,4,6) #linspace with create with specific number of elements

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
# 6 is the number of equally spaced elements given starting and end point
# between 1 to 4, 6 elements

In [6]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [4]:
a.shape

(2, 3, 3)

In [5]:
a.ndim

3

In [ ]:
np.indices((2,2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [ ]:
a = np.array([1,2,3])

In [ ]:
print(a.dtype)  #to check the datatype of elements of array

int64


# numpy array vs list memory allocation

In [ ]:
# difference between list and array
# array takes less memory compared to list
# array are fast and convenient

In [ ]:
l = range(100)
import sys

a = 10
print(sys.getsizeof(a)) # memory allocated to a

print(sys.getsizeof(a)*len(l))

28
2800


In [ ]:
a = np.arange(100)
print(a.size*a.itemsize)


800


# speed

In [ ]:
import time

In [ ]:
size = 1000000
l1 = range(size)
l2 = range(size)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)] #list comprehension
print((time.time()-start)*1000)

140.99478721618652


In [ ]:
n1 = np.arange(size)
n2 = np.arange(size)

start = time.time()
result1 = n1+n2
print((time.time()-start)*1000)

5.541086196899414


In [ ]:
# numpy operations

a = np.array([[1,2,3],[10,20,30]])
print(a.ndim)

2


In [ ]:
print(a.itemsize)

8


In [ ]:
print(a.dtype)

int64


In [ ]:
a.shape

(2, 3)

In [ ]:
a.size

6

# Reshape

In [ ]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
a.reshape(3,2)

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

In [ ]:
# slicing

a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
a[0,0]  #accessing individual elements

1

In [ ]:
a[0,1]

2

In [ ]:
a[0:,1]

array([ 2, 20])

In [ ]:
a[0:2,1:]

array([[ 2,  3],
       [20, 30]])

In [ ]:
a = np.array([[1,2,3,4,5], [10,20,30,40,50]])
a.shape

(2, 5)

In [ ]:
a[1,2:4]

array([30, 40])

In [ ]:
a.min()

1

In [ ]:
a.max()

50

In [ ]:
a.sum()

165

In [ ]:
print(a)
print(np.sum(a,axis = 0)) # axis = 0 is column wise sum

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
[11 22 33 44 55]


In [ ]:
#axis = 1 row wise

In [ ]:
#array mathematical operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x+y)

[[ 6  8]
 [10 12]]


In [ ]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [ ]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [ ]:
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [ ]:
a = np.array([0,1,2,3,4,5])
a = a.reshape(3,2)
print(a)
np.reshape(a,(2,3))

[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.reshape(a,6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.size

6

In [ ]:
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [ ]:
pip install pandas

# Pandas

In [ ]:
'''
data types of pandas
series
data frames
panel
'''

'\ndata types of pandas\nseries\ndata frames\npanel\n'

In [ ]:
import pandas as pd


In [ ]:
a = np.array(['g','o','e','d','u','h','u','b'])
p = pd.Series(a)
print(p)

0    g
1    o
2    e
3    d
4    u
5    h
6    u
7    b
dtype: object


In [ ]:
# conversion of numpy array to pandas series

In [ ]:
# numpy array don't have indices
# pandas series has indices

In [ ]:
s1 = pd.Series(np.random.random(5), index = ['a','b','c','d','e'])

In [ ]:
print(s1)

a    0.320828
b    0.845625
c    0.745873
d    0.882590
e    0.769902
dtype: float64


In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
s1.dtype

dtype('float64')

In [ ]:
data = {'pi':3.14,'e':2.71}
print(data)
s3 = pd.Series(data)
print(s3)

{'pi': 3.14, 'e': 2.71}
pi    3.14
e     2.71
dtype: float64


In [ ]:
s = pd.Series(np.random.random(5))

In [ ]:
print(s)

0    0.164071
1    0.700528
2    0.173472
3    0.068502
4    0.355660
dtype: float64


In [ ]:
s[1]

0.7005282952091355

In [ ]:
s[1:3]

1    0.700528
2    0.173472
dtype: float64

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s.size

5

In [ ]:
s.shape

(5,)